### PR TITLE
add async deep equals engine

### PR DESCRIPTION
**Pull request by FrontMage**
#19

### CODE REVIEW

**Comment by nadeesha** [comment]
This looks really good! Would you mind adding an entry in the README for this as well?

Just after `~deep-equals` entry would do.

**Comment by FrontMage** [comment]
Sure, I'm on it.

**Comment by nadeesha** [comment]
Thanks @FrontMage! One problem that just occurred to me was that jest won't support this unless you return the promise. 

And probably, it's more idiomatic if we resolve the resolvable results before asserting - without having another engine to do that. I will give this some thought. When I've drawn a solution, I'll accept this PR and work on it.

Given that, hope you don't mind if I take a little bit of time before merging this.

**Comment by nadeesha** [comment]
Hi @FrontMage, I've absorbed your engine and moved your code to `~equals` engine to resolve if a promise returns. Thanks for the contribution.

**Pull request merged**
